### ISSUE TITLE
Import both type and it's constructor under the same name

### ISSUE THREAD

**Issue by mcheshkov** [electron/electron-typescript-definitions#55]
I want to be able to write code like that
```ts
import {BrowserWindow} from "electron";
let win: BrowserWindow;
win = new BrowserWindow();
```
But it gives me `error TS2304: Cannot find name 'BrowserWindow'.` on type of `win`

This code
```ts
import * as e from "electron";
let win: Electron.BrowserWindow;
win = new Electron.BrowserWindow();
```
compiles to 
```js
let win;
win = new Electron.BrowserWindow();
```
which is invalid since it's relying on global `Electron` and not on imported one. And from source it's unclear where did `Electron` even come from.

My suggestion: replace namespace with module and proper class exports in type definitions. Like this
```ts
declare module 'electron' {
  export class BrowserWindow { /*...*/ }
}
```
With this first example will compile fine to
```js
const electron_1 = require("electron");
let win;
win = new electron_1.BrowserWindow();
```

**Comment by MarshallOfSound** [comment]
> replace namespace with module and proper class exports in type definitions

Personally, I really don't like this, having the class type and the class itself as separate entities gives you much more freedom.  That and the global namespace is already in use in the definitelytyped definitions.

**Comment by mcheshkov** [comment]
What exact freedom it gives you? Other than "to write code that use nonexistent global variables, and have it compiled without any warning"?
Jokes aside, what is the purpose of having ambient namespace, if actual electron environment does not have it, and you got to require/import stuff?

**Comment by MarshallOfSound** [comment]
@mcheshkov Well there are quite a few reasons that come to mind, the easiest of which to explain is performance.

If in order to get the type we have to import a module from another file that results in a whole bunch of `fs` and `path` calls which when you add them up significantly slow down your application.

The freedom I refer to is the ability for instance to refer to a type without having to import the module.  E.g. Declaring a utility function like so

```js
export default (window: Electron.BrowserWindow) => {

}
```

I think the separation is the better way to do things but others might have a different opinion so we'll see what they think 👍

**Comment by zeke** [comment]
I think @DanielRosenwasser was saying something about global `Electron` being an issue. Can you elaborate on that?

**Comment by mcheshkov** [comment]
OK, I got the point on depending only on type, and not on actual module. Can't say that about `fs` and `path` calls, need to measure that since module cache make this nontrivial.

> type definitions aren't global variables

I understand that, but compiled code is still the same. One can use `new Electron.BrowserWindow` without any warning, and to use resulting code as is one have to declare variable `Electron` somewhere. That's the opposite of importing value where only type is needed.

```
type A = Electron.BrowserWindow;
let a : A;
a = new Electron.BrowserWindow();
// a = new A(); // invalid
```

In this case last line will give `TS2693:'A' only refers to a type, but is being used as a value here.`

So maybe there could be only type aliases or interfaces in namespace, and classes in module, to allow type checking without actually introduce runtime dependency.

Nodejs typings actually do something like that, declaring a little bit of interfaces in global namespace, and only a single class (that's EventEmitter, IDK why, only place using it besides reimplementing and reexporting as a class in `events` is undocumented `_debugger`), and then defining all the classes in their respective modules, and importing other required types in declarations.

Excerpt from `@types/node/index.d.ts`
```ts
declare module "cluster" {
    import * as events from "events";
    export class Worker extends events.EventEmitter {
    }
}
```

That's the single place where `Worker` is defined, and to use it one have to require/import it.

**Comment by DanielRosenwasser** [comment]
> I think @DanielRosenwasser was saying something about global `Electron` being an issue. Can you elaborate on that?

The problem is that without an `import` or `export`, everything in that file has been declared globally. What you really want to do is have a top-level

```ts
export = Electron;
```

which will tell TS that any importers of `"electron"` will actually be referencing the type/shape of `Electron`.

The downside is that you'll need to move your declaration of `original-fs` elsewhere - is that a module Electron magically makes available?

**Comment by mode777** [comment]
I would strongly favour the declaration of a module instead of a namespace (sometimes also called ambient module)

- @mcheshkov is absolutely right when arguing that if you can write `a = new Electron.BrowserWindow();` you should also be able to do `myConstructor = Electron.BrowserWindow`. Because that's how typescript types usually work - they are constructors. Why astonish the user?
- Namespaces are a legacy feature. Namespace declarations are build for Browser-libs like jQuery where you import the library in a script tag and you let the ts-compiler know there is a global object. I'm new to electron but I doubt someone will include it via a script tag (Is this even possible?)
- Strongest point IMO: Why do it different than every other node library I can think of (including node itself? Just as npm modules are slowly becoming the accepted way of distributing a js library, distributing the module itself alongside a "@ types/*" package with the typings for the __module__ (not the namespace) seems to become the standard-way of doing things and making typescript developement easier.

@MarshallOfSound, I do not agree with, that it requires additional overhead (at least for the runtime). I'm pretty sure "require"-calls are cached and why would you like to use it's types if you don't intend to load the module.

**Comment by MarshallOfSound** [comment]
>  is absolutely right when arguing that if you can write a = new Electron.BrowserWindow(); you should also be able to do myConstructor = Electron.BrowserWindow. Because that's how typescript types usually work - they are constructors. Why astonish the user?

Tp be honest I think it's a flaw in typescript if at write-time there isn't anything warning you it is just a type declaration not an actual implementation 😆 maybe there's been a discussion about this somewhere already or they can't statically analyze to determine that.

> Namespaces are a legacy feature. Namespace declarations are build for Browser-libs like jQuery where you import the library in a script tag and you let the ts-compiler know there is a global object. I'm new to electron but I doubt someone will include it via a script tag (Is this even possible?)

I'd like to see a thing in the typescript docs that says namespaces are legacy, I see lots of people still using them including big ones like Node.JS.  To me having a global namespace is critical as I want to use the typings in other typing declarations without importing `electron`.  For instance

```js
export interface WindowManager {
  add(win: Electron.BrowserWindow): void;
}
```

> Why do it different than every other node library I can think of (including node itself?

We aren't doing it differently, especially not to node.

[NodeJS](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cce31af92dc06fbd620d48ff55a9904be20ddc61/node/index.d.ts#L249), [all the others](https://github.com/DefinitelyTyped/DefinitelyTyped/search?p=1&q=%22declare+namespace%22&type=&utf8=%E2%9C%93)

> I do not agree with, that it requires additional overhead (at least for the runtime). I'm pretty sure "require"-calls are cached and why would you like to use it's types if you don't intend to load the module.

I have the numbers to back this claim up, any time you use `require` it recursively determines valid paths to attempt to require along your search paths **regardless of the module cache**.  The module cache only kicks in once the actual path to the JS file has been resolved, before that happens `fs.realpath` and `fs.lstatSync` will have been called many times and they are quite costly functions especially when they are only their for types.

**Comment by mode777** [comment]
@MarshallOfSound thanks for the follow up. You might have some valid points there. Still I haven't changed my mind but maybe there is a compromise...

* Typescript doc doesn't say that namespaces are a legacy features. However the example for ambient namespace declarations is exactly the global-object/imported-by-script-tag one I was talking about.

> The popular library D3 defines its functionality in a global object called d3. Because this library is loaded through a <script> tag (instead of a module loader), its declaration uses namespaces to define its shape.

* You actually can use an import for types only and the typescript compiler won't generate a require statement at all - no overhead here. This way you have also explicitly statet your dependency on electron instead of just implicitly using its namespace

Typescript
```ts
import {EventEmitter} from "events";
let a: EventEmitter = null;
```
Compiles to
```js
"use strict";
let a = null;
```

* I had a closer look at the NodeJs typings and they actually support both arguments as they seem to declare the types on the namespace __as well as__ the namespace. So you could write the above example like this:
```ts
let b: NodeJS.EventEmitter = null;
```

So maybe electron should do this too and keep everyone happy?

One note on DefinitelyTyped: It has been around for ages in Typescript-time and, unlike npm-modules it has to be unbiased of the environment it is used in. A lot of these libraries are indeed used as global object imported with a script tag as this is (sadly) still very common in client-side dev.

**Comment by mizzle-mo** [comment]
As a first time user of these new declarations I am stuck on this.  Literally 2 minutes into using them I am stuck with this:

![image](https://user-images.githubusercontent.com/6625993/26982858-65936a58-4cff-11e7-80fc-e48ab1a6fd9e.png)

I m just trying to convert the main.js from the quick start to .ts.  How do I work around this?

**Comment by mizzle-mo** [comment]
Just wanted to add this is a very jarring experience for users.  I just spent 20 minutes trying to figure out why TypeScript was telling me something I just imported cannot be found.

**Comment by mizzle-mo** [comment]
This needs to be fixed.  Right now I can't get started at all and the @types/electron that used to work is now stubbed pointing to use the built-in declarations.  Do we really have to type mainWindow as any or am I missing something?

**Comment by zeke** [comment]
I agree that it's not intuitive to have to use the `Electron.` prefix when it's not explicitly declared in the file.

> I had a closer look at the NodeJs typings and they actually support both arguments as they seem to declare the types on the namespace as well as the module. 

☝️ This sounds like a nice middle ground to me, @mode777

**Comment by mizzle-mo** [comment]
@zeke you unblocked me, I missed the part about it being a Global above.  Thank you!

**Comment by mtpultz** [comment]
With the addition of typings and the issue being discussed would it make sense to have a second quick start for typescript?  I mentioned this yesterday https://github.com/electron/electron/issues/10002 after having the same issue as @mcheshkov, and not understanding why this was the case even after looking at the source.  I know electron is framework agnostic, but by providing typings any implementation decisions you make regarding there use could easily be documented by an equivalent quick start example.

**Comment by zeke** [comment]
> would it make sense to have a second quick start for typescript?

I think this would be very helpful for folks starting with Electron and TypeScript, especially given that we are now implicitly endorsing the use of TypeScript by vendoring our own type definition file.

However, we on the Electron team at GitHub are not regular TypeScript users and are by no means experts. If someone in the community would be willing to start a new `electron-quick-start-typescript` repository, I personally would be happy to get involved and help steer it into becoming something we could comfortable point new users to.

**Comment by darsain** [comment]
To sum this issue up, the current Electron type declarations:

- force people into using implicit global namespaces for accessing interfaces like it's 2005
- disallow intuitive TypeScript types usage conventions

Especially the 2nd point makes life for TypeScript newbies (such as myself this morning) a chore, since the intuitive convention how to consume and use types:

```js
import {BrowserWindow} from 'electron';
let win: BrowserWindow;
```

throws `[ts] Cannot find name 'BrowserWindow'.` error, and I had to spent half an hour figuring out that I have to use an undocumented global `Electron.` namespace to access these interfaces. I only figured it out by deduction upon reading the `node_modules/electron/electron.d.ts` file. A great development workflow for sure! 😢

Even @DanielRosenwasser, an engineer on TypeScript told you above that this is a problem and how to solve it, and it still didn't convince you?

The only argument against this I can recall after reading this thread is that having to import from `electron` just to access interfaces introduces a module system overhead, but that was quickly rebutted by the fact that if you import only to access an interface but don't actually use the module, the resulting build will **not** have the import/require statement included, and it will be used only to type check, which is exactly how I would expect an intelligent compiler to work. And even if this was an issue, the compromise suggested by people here - to declare **both** the module shape and the global namespace - would fix it, and allow people who prefer using globals to continue using globals (for whatever reason).

I hope this summary of the state of this issue will help nudge it out of the limbo and we will get an awesome and seamless TypeScript experience in our electron projects soon. Please? 😄❤️

Especially since it's apparently a trivial fix. Helpful people in TypeScript gitter gave me this super simple diff that would make my life fun again:

```diff
  declare module 'electron' {
--  const electron: Electron.AllElectron;
--  export = electron;
++  export = Electron;
  }
```

Tested it by modifying `node_modules/electron/electron.d.ts` and it made things work exactly as I would expect from the get go. But there might be some `original-fs` declaration issues to be tweaked out as mentioned by @DanielRosenwasser above? Not sure, I'm really a TypeScript newbie at the moment.

**Comment by MarshallOfSound** [comment]
@darsain To be clear, if someone can submit a non-breaking, test-passing PR that introduces support for the non-global typings I would totally accept it.  I just don't have the bandwidth to look at this right now 😄

**Comment by darsain** [comment]
@MarshallOfSound can I hold you up to your word and make you look at #78? :)

**Comment by vanessayuenn** [comment]
@zeke @mtpultz I quickly ported over electron-quick-start to using typescript [here](https://github.com/electron/electron-quick-start-typescript). Feel free to improve upon it if need be. :)

**Comment by zeke** [comment]
This is fixed thanks to @NaridaL, and will land in the next release of Electron.

**Comment by mustafaKamal-fe** [comment]
Hello from the future. okay i was reading through the thread and got a bit confused.. would you explaing in one sentence why do i still need to use:
`someFunction(mainWindow: Electron.BrowserWindow) {...}`
while this is not working and typescript is not happy!!
`import {BrowserWindow} from 'electron';`
`someFunction(mainWindow: BrowserWindow) {...} `
