### ISSUE TITLE
electron.d.ts error using TS2.6.0-rc in strict mode

### ISSUE THREAD

**Issue by xaviergonz** [electron/electron-typescript-definitions#79]
```
node_modules/electron/electron.d.ts(5390,13): error TS2430: Interface 'WebviewTag' incorrectly extends interface 'HTMLElement'.
  Types of property 'addEventListener' are incompatible.
      Type '{ (event: "load-commit", listener: (event: LoadCommitEvent) => void, useCapture?: boolean | undef...' is not assignable to type '{ <K extends "error" | "waiting" | "progress" | "ended" | "change" | "input" | "select" | "abort"...'.
        Types of parameters 'listener' and 'listener' are incompatible.
          Type 'EventListenerOrEventListenerObject' is not assignable to type '(event: LoadCommitEvent) => void'.
            Type 'EventListenerObject' is not assignable to type '(event: LoadCommitEvent) => void'.
              Type 'EventListenerObject' provides no match for the signature '(event: LoadCommitEvent): void'.
```

I think it is due to this new strict change:
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#strict-function-types

**Comment by sandersn** [comment]
This happens because the addEventListener/removeEventListener overloads in WebviewTag are incorrect. When you override a method in Typescript, the overloads of the base's method are *not* copied to the overriding method in the derived class. They're just checked for compatibility. You have to copy them yourself if you want them.

Typescript 2.6 catches this because of strict function types, although it missed it before. The fix is to copy the add/RemoveEventListener overloads from HTMLElement to the very bottom of the list of overloads in WebviewTag. 

I'll do it this afternoon if I can figure out how to build electron.d.ts.

**Comment by styfle** [comment]
Thanks for fixing!

I am still getting [the same error](https://travis-ci.org/styfle/magnemite/jobs/301135712#L550).

Was this changed released yet, and if so which version?

**Comment by MarshallOfSound** [comment]
@styfle This change will only take affect in Electron versions released after #81 was merged

**Comment by ccorcos** [comment]
Me too!

**Comment by vladimiry** [comment]
There is no such issue with the latest electron@1.8.2-beta.3 version.

**Comment by KeitaIkeda** [comment]
Hi guys
I'm using Electron: 1.8.2, but still encountering this issue.

How to fix it?

```
let webview: WebviewTag = document.getElementById('mainWebview')!;
```
